# Generated by Django 2.2 on 2020-08-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsAppBot', '0006_mensajes_confirmacion_denegada'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='comando_invalido',
            field=models.CharField(default='Comando no valido', max_length=255),
            preserve_default=False,
        ),
    ]
