# Generated by Django 2.2 on 2020-08-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsAppBot', '0007_mensajes_comando_invalido'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='confirmacion_exitosa',
            field=models.CharField(default='Confirmacion Exitosa', max_length=255),
            preserve_default=False,
        ),
    ]
