# Generated by Django 2.2 on 2020-08-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsAppBot', '0008_mensajes_confirmacion_exitosa'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='comandos_disponibles',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensajes',
            name='ya_confirmado',
            field=models.CharField(default='Ya estas confirmado como', max_length=255),
            preserve_default=False,
        ),
    ]
