# Generated by Django 2.2 on 2020-08-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsAppBot', '0009_auto_20200824_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='mensaje_final',
            field=models.CharField(default='Despues de 60 minutos, la conexion se rompera y tendra que ingresar _join practical-realize_ para reconectar', max_length=255),
            preserve_default=False,
        ),
    ]
