# Generated by Django 2.2 on 2020-08-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsAppBot', '0010_mensajes_mensaje_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitado',
            name='cambio_nombre',
            field=models.BooleanField(default=False),
        ),
    ]
