# Generated by Django 2.2 on 2020-08-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsAppBot', '0011_invitado_cambio_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitado',
            name='sexo',
            field=models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=2),
        ),
    ]
